2025-04-26 12:48:09,287 - INFO - fuzzer - Running deleteRepoFuzzer() from fuzzer_adrian
2025-04-26 12:48:09,287 - INFO - fuzzer - None
2025-04-26 12:48:09,287 - INFO - fuzzer - Running dumpContentIntoFileFuzzer()
2025-04-26 12:48:09,287 - INFO - fuzzer - None
2025-04-26 12:48:09,287 - INFO - fuzzer - Running makeChunksFuzzer()
2025-04-26 12:48:09,287 - INFO - fuzzer - None
2025-04-26 12:48:09,287 - INFO - fuzzer - Logging constructHelmStringFuzzer() from graphtaint.py:
2025-04-26 12:48:09,287 - ERROR - fuzzer - An error occurred:
Traceback (most recent call last):
  File "/home/adrian/SQA/FailSafe-SQA2025-AUBURN/KubeSec/KubeSec-master/fuzz.py", line 28, in fuzzer
    logger.info("Result %s", constructHelmStringFuzzer())
                             ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/adrian/SQA/FailSafe-SQA2025-AUBURN/KubeSec/KubeSec-master/graphtaintFuzzer.py", line 7, in constructHelmStringFuzzer
    print("Trying input: 123", constructHelmString(123))
                               ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/home/adrian/SQA/FailSafe-SQA2025-AUBURN/KubeSec/KubeSec-master/graphtaint.py", line 23, in constructHelmString
    upper_key, key, _ = hiera_tuple
    ^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable int object
